// server/models/Category.ts
import { Schema, model, models, type Document, type Types } from 'mongoose'

// ---------------------------------------------------------------------------
// 1. TypeScript Interface
// In TypeScript, an "interface" is like a blueprint. It describes what
// fields exist on a Category document so your editor knows what to autocomplete
// and can warn you if you spell a property name wrong in your code.
// ---------------------------------------------------------------------------
export interface ICategory extends Document {
  // Multilingual name for customer display across all three store languages
  name: {
    ar: string // Arabic (primary store language) 
    sv: string // Swedish 
    en: string // English 
  }

  // Multilingual URL slugs for localized routing (e.g. /sv/kategori/kryddor) 
  /**
   * In web development, a slug is the part of a URL that identifies a specific page or resource using readable words instead of a raw database ID.
   * If you didn't use slugs, your category URLs would look like this: /sv/kategori/64ef876970bd9596e9bb4567
   * With slugs, they look like this: /sv/kategori/kryddor (spices)
   * This is much better for SEO and user experience.
   */
  slug: {
    ar: string
    sv: string
    en: string
  }

  // Optional link to a parent category for building sub-categories (e.g. Pantry -> Spices)
  // The '?' and '| null' mean this field is optional
  parentId?: Types.ObjectId | null

  // Controls whether the category appears in menus and product navigation
  isActive: boolean

  // Order priority for rendering header menus (lower numbers appear first)
  sortOrder: number

  // Automatic timestamp fields generated by Mongoose
  createdAt: Date
  updatedAt: Date
}

// ---------------------------------------------------------------------------
// 2. Mongoose Schema
// The schema is the actual database definition. While TypeScript checks your
// code during editing/building, Mongoose enforces these rules in MongoDB at runtime.
// ---------------------------------------------------------------------------
const CategorySchema = new Schema<ICategory>(
  {
    name: {
      ar: { type: String, required: true, trim: true },
      sv: { type: String, required: true, trim: true },
      en: { type: String, required: true, trim: true },
    },
    slug: {
      // index: true makes finding categories by their URL slug very fast
      ar: { type: String, required: true, trim: true, lowercase: true, index: true },
      sv: { type: String, required: true, trim: true, lowercase: true, index: true },
      en: { type: String, required: true, trim: true, lowercase: true, index: true },
    },
    parentId: {
      type: Schema.Types.ObjectId,
      ref: 'Category', // References this same model to enable parent-child relationships
      default: null,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
    sortOrder: {
      type: Number,
      default: 0,
    },
  },
  {
    // Automatically creates and updates 'createdAt' and 'updatedAt'
    timestamps: true,
  }
)

// ---------------------------------------------------------------------------
// 3. Model Export
// Nuxt 3 reloads server files during development. Checking 'models.Category'
// first prevents Mongoose from crashing with an "OverwriteModelError".
// ---------------------------------------------------------------------------
export const Category = models.Category || model<ICategory>('Category', CategorySchema)